### ISSUE TITLE
Run VAD on Microphone Input Signal

### ISSUE THREAD

**Issue by jhoelzl** [marsbroshok/VAD-python#1]
Hello,

is there also an option to run this VAD on a frame (e.g. 30ms) of an microphone input signal?
Would be nice to provide an example script using PyAudio and this module.

Regards,
Josef

**Comment by marsbroshok** [comment]
Hello Josef,

Sadly I'm not working on this module anymore, but you are kindly invited to fork it and add microphone/PyAudio support.

Best regards,
Alexander.
