### ISSUE TITLE
Not working with this wav (file attached)

### ISSUE THREAD

**Issue by kovalroma** [marsbroshok/VAD-python#15]
Hello, 
I am radio amateur and trying to find solution to detect voice in VHF audio record. 
I have this [sample](https://mega.nz/file/74h1DIwL#HsZ5MNcpif9xrbfP610vnbelvN-HxSfClV5TixlzJwY) without voice, but you algorithm detect it.

**Comment by marsbroshok** [comment]
Hi, the detection algorithm in my code is basic. It checks the energy of voice frequencies (https://en.wikipedia.org/wiki/Voice_frequency) and use it to "detect" speech. I guess in your case there is noise in the speech frequencies as well so there is some energy and it triggers the detection. 

**I'm not working on this project anymore**.
I advise everyone curious about voice detection to have a look at some more modern approaches using deep learning, like:
 - https://www.mathworks.com/help/audio/examples/voice-activity-detection-in-noise-using-deep-learning.html
 - https://medium.com/vivolab/vivovad-a-voice-activity-detection-tool-based-on-recurrent-neural-networks-32356526321c
 - https://github.com/hcmlab/vadnet

**Comment by RicherMans** [comment]
Hey there, I don't want to hijack your work here @marsbroshok , but I just came across this post randomly and would like to propose my recent work using weakly supervised training as a possible solution.  
@kovalroma if you like, check out [GPVAD](https://github.com/RicherMans/GPV)

I also ran your file over my model, it predicts correctly nothing.
