### ISSUE TITLE
An error occurred running the code

### ISSUE THREAD

**Issue by edisonzhao1996** [marsbroshok/VAD-python#7]
C:\Users\PC\PycharmProjects\untitled\Net resource\vad.py:150: RuntimeWarning: invalid value encountered in double_scalars
   speech_ratio = sum_voice_energy / sum_full_energy

The above is an error that occurred when I ran the following code. How can I solve this problem？

> from vad import VoiceActivityDetector
> filename = r'C:\Users\PC\PycharmProjects\untitled\audio\test.wav'
> v = VoiceActivityDetector(filename)
> v.plot_detected_speech_regions()

**Comment by marsbroshok** [comment]
Hello, I see that you are using windows, maybe it is an error related to this. I was running this code on Linux.
