### ISSUE TITLE
bug in text

### ISSUE THREAD

**Issue by smartadpole** [marsbroshok/VAD-python#8]
你想用 ratio ，却写成了 ration in：

Basic Idea
Input audio data treated as following:

- Convert stereo to mono
- Move a window of 20ms along the audio data
- Calculate ration between energy of speech band and total energy for window
- If ratio is more than threshold (0.6 by default) label windows as speech
- Apply median filter with length of 0.5s to smooth detected speech regions
- Represent speech regions as intervals of time

**Comment by marsbroshok** [comment]
Thank you, typo is fixed!
